# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    tags:
      - 'V*'
  pull_request:
    branches: [ main ]

jobs:
  Compile:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: |
        ./gradlew compileJava
        ./gradlew processResources
        ./gradlew classes



  Test:
    needs: Compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test the project
      run: |
        ./gradlew compileTestJava
        ./gradlew processTestResources
        ./gradlew testClasses
        ./gradlew test
    - uses: actions/upload-artifact@v2
      with:
        name: TestReport
        path: build/reports/tests/test
      
  Assemble:
    needs: [Compile, Test]
    runs-on: ubuntu-latest
    outputs:
      jar_name: ${{ steps.step_get_jar_name.outputs.jar_name }}
      artifact_jar_name: ${{ steps.step_get_artifact_jar_name.outputs.jar_name }} 
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11      
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Output jar
      run: |
        ./gradlew jar
        ./gradlew assemble
    
    - id: step_get_jar_name
      run: echo "::set-output name=jar_name::$(find ./build/libs -name '*.jar' -exec basename {} \;)"
    - id: step_get_artifact_jar_name
      run: echo "::set-output name=jar_name::buildJar"
      
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.step_get_artifact_jar_name.outputs.jar_name }}
        path: build/libs/*.jar
            
